
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: car_locator_development
  user: postgres
  password: deploy

test:
  <<: *default
  host: db
  database: car_locator_test
  user: postgres
  password: deploy
